### PR TITLE
feat: adds resize observer to RenderManager

### PR DESCRIPTION
**Pull request by luigidenora**

### CODE REVIEW

**Comment by luigidenora** [comment]
@agargaro Could you test the example to make sure it’s all good? Thanks!

**Comment by agargaro** [comment]
#fix 99 

@luigidenora  I removed the debounce callback, I think it's cleaner now. What do you think?

**Review by agargaro — APPROVED** [review]

**Comment by luigidenora** [comment]
> #fix 99
> 
> @luigidenora I removed the debounce callback, I think it's cleaner now. What do you think?

Makes sense, I’d say it’s perfect this way.

**Comment by agargaro** [comment]
fix #99

**Pull request merged**
